server:
  port: 8080

spring:
  application:
    name: euler-cloud-uc
  datasource:
    url: jdbc:mysql://localhost:3306/euler_cloud_uc?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
  redis:
    host: localhost
    port: 6379

euler:
  application:
    runtime-path: /var/run/eulerprojects/${spring.application.name}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
